services:
  caddy:
    image: caddy:2.8.4-alpine
    container_name: caddy.sphinx
    restart: unless-stopped
    command: caddy reverse-proxy --from https://${DOMAIN}:443 --to http://mcp.sphinx:3000
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy:/data
    depends_on:
      - mcp

  mcp:
    image: sphinxlightning/repo2graph:latest
    restart: on-failure
    container_name: mcp.sphinx
    environment:
      - PORT=3000
      - NEO4J_HOST=neo4j.sphinx:7687
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    ports:
      - 3000:3000
    depends_on:
      - neo4j

  neo4j:
    image: sphinxlightning/sphinx-neo4j:latest
    container_name: neo4j.sphinx
    user: "1000:1000"
    volumes:
      - ./.neo4j/data:/data:rw
      - ./.neo4j/logs:/logs:rw
      - ./.neo4j/plugins:/plugins:rw
      - ./.neo4j/tmp/import:/import
      - ./conf:/conf/
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
    command: >
      /bin/bash -c "
      cp -R /var/lib/neo4j/plugins/* /plugins &&
      /startup/docker-entrypoint.sh neo4j
      "
    healthcheck:
      test:
        [
          "CMD",
          "/var/lib/neo4j/bin/cypher-shell",
          "-u",
          "neo4j",
          "-p",
          "${NEO4J_PASSWORD}",
          "MATCH (n) RETURN n LIMIT 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 20

volumes:
  caddy:
